# Generated by Django 5.1.3 on 2024-11-08 21:19

import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Категория')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.generic_image_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Подкатегория')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.generic_image_path, verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегорию',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('id',),
            },
        ),
    ]
